/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRouteImport } from './routes/indexRoute'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticateIndexImport } from './routes/authenticate/index'

// Create/Update Routes

const IndexRouteRoute = IndexRouteImport.update({
  id: '/indexRoute',
  path: '/indexRoute',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticateIndexRoute = AuthenticateIndexImport.update({
  id: '/authenticate/',
  path: '/authenticate/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/indexRoute': {
      id: '/indexRoute'
      path: '/indexRoute'
      fullPath: '/indexRoute'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/authenticate/': {
      id: '/authenticate/'
      path: '/authenticate'
      fullPath: '/authenticate'
      preLoaderRoute: typeof AuthenticateIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/indexRoute': typeof IndexRouteRoute
  '/authenticate': typeof AuthenticateIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/indexRoute': typeof IndexRouteRoute
  '/authenticate': typeof AuthenticateIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/indexRoute': typeof IndexRouteRoute
  '/authenticate/': typeof AuthenticateIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/indexRoute' | '/authenticate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/indexRoute' | '/authenticate'
  id: '__root__' | '/' | '/indexRoute' | '/authenticate/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndexRouteRoute: typeof IndexRouteRoute
  AuthenticateIndexRoute: typeof AuthenticateIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndexRouteRoute: IndexRouteRoute,
  AuthenticateIndexRoute: AuthenticateIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/indexRoute",
        "/authenticate/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/indexRoute": {
      "filePath": "indexRoute.tsx"
    },
    "/authenticate/": {
      "filePath": "authenticate/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
